FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

# Create the directory with appropriate permissions
RUN mkdir -p node_modules/.cache && chown -R node:node /app

USER node

# Set permissions for the .cache directory
RUN chmod -R 777 node_modules/.cache

RUN npm install

COPY . .

CMD [ "npm", "run", "start" ]


